on: push
jobs:
  clippy-check:
    name: ğŸ§ Clippy Check
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
  fmt-check:
    name: ğŸ‘€ Fmt Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Fmt
        run: cargo fmt --all -- --check
  build-check:
    name: ğŸ”¨ Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Try To Build
        run: cargo build --release
  cargo-test:
    name: ğŸ¦€ Cargo Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Checks
        run: cargo test
