on: push
jobs:
  clippy-check:
    name: ğŸ§ Clippy Check
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
  fmt-check:
    name: ğŸ‘€ fmt Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Fmt
        run: cargo fmt --all -- --check
